### ISSUE TITLE
缺少了关于 miniprogram api 的类型定义

### ISSUE THREAD

**Issue by lqloveball** [wtto00/jweixin-esm#15]
wx.miniProgram.navigateBack	参数与小程序接口一致	[1.6.4](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
wx.miniProgram.switchTab	参数与小程序接口一致	[1.6.5](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
wx.miniProgram.reLaunch	参数与小程序接口一致	[1.6.5](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
wx.miniProgram.redirectTo	参数与小程序接口一致	[1.6.5](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
wx.miniProgram.postMessage	向小程序发送消息，会在以下特定时机触发组件的message事件：小程序后退、组件销毁、分享、复制链接（[2.31.1](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)）	[1.7.1](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
wx.miniProgram.getEnv	获取当前环境	[1.7.1](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)

关于小程序的API 接口没有定义

**Comment by wtto00** [comment]
已更新 [NPM v1.6.0-3](https://www.npmjs.com/package/@wtto00/jweixin-esm)
