### ISSUE TITLE
package.json exports types

### ISSUE THREAD

**Issue by forzgc** [wtto00/jweixin-esm#17]
package.json 中 exports配置和types配置冲突了，导致ts类型声明无效。

**Comment by wtto00** [comment]
可以提供一个示例工程吗？请看下方两个示例，都能正常工作的。

react+ts
https://stackblitz.com/edit/stackblitz-starters-ewvonf?file=src%2Findex.tsx
![image](https://github.com/wtto00/jweixin-esm/assets/30424139/397b78c4-f680-4dde-8f3e-4ab03bed74ce)


vue+ts
https://codesandbox.io/p/sandbox/hopeful-brahmagupta-yhwdmc?welcome=true
![image](https://github.com/wtto00/jweixin-esm/assets/30424139/04328c94-57ce-4dd6-a448-000f15954524)

**Comment by wtto00** [comment]
@forzgc 请确认使用的是最新版本`^1.6.0-3`版本，`1.6.0`版本有问题

**Comment by forzgc** [comment]
确定使用了 ^1.6.0-3 版本，项目是 vite + vanilla-ts。

https://stackblitz.com/edit/vitejs-vite-pgtps6?file=src%2Fmain.ts&terminal=dev

猜测是vite默认ts配置比较严格（具体是哪个配置我还不知道），导致使用 exports: string 配置时会覆盖types配置。
本地改成下面的配置后错误消失。

```
"exports": {
    ".": {
      "import": "./lib/jweixin-1.6.0.esm.js",
      "types": "./lib/index.d.ts"
    }
  },
```

我对这package.json方面的理解还很浅，上面的配置仅参考。

**Comment by wtto00** [comment]
@forzgc 感谢反馈。

经过测试是因为 tsconfig 中，`moduleResolution`配置项为`bundler`和`node16`时，无法识别到类型；更改为`node`或者`nodenext`就可以了。

[v1.6.0-4](https://www.npmjs.com/package/@wtto00/jweixin-esm/v/1.6.0-4)已更新在 NPM 上，对比做了兼容。
